# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PB
email: public@pascalbrokmeier.de
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer, student, traveler and tech geek.
  I always look for new projects and exciting things to read about or try myself.
  I do mostly web development and NodeJS with some Java, Python and C here and there.
  For years I worked as a software developer at a German consulting company and for a time at an Australian cloud drone startup,
  but now live in Naples, Italy to write my master thesis about Neural Networks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pascalbrokmeier.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PascalBrokmeier
github_username:  pascalwhoop
full_name: Pascal Brokmeier
short_name: Pascal
blog_link: "https://medium.com/curiouscaloo"
unsplash_link: "https://unsplash.com/@pascalwhoop"
# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - node_modules
   - dev-scripts
   - package.json
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
