baseURL = "https://pascalbrokmeier.de/"
languageCode = "en-us"
title = "Pascal Brokmeier"
theme= "hello-friend-ng"

[menu]
#    [[menu.main]]
#      identifier = "blog"
#      name       = "Blog"
#      url        = "/posts"
    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "My personal blog and digital business card"

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Homepage and blog of Pascal Brokmeier"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "email"
    url  = "mailto:public@pascalbrokmeier.de"

  [[params.social]]
    name = "github"
    url  = "https://github.com/github"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/pascalbrokmeier"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/1170940/pascalwhoop"

  [[params.social]]
    name = "unsplash"
    url  = "https://unsplash.com/@pascalwhoop"
    
  [[params.social]]
    name = "telegram"
    url  = "https://telegram.me/pascalwhoop"

  [[params.social]]
    name = "keybase"
    url  = "https://keybase.io/pascalbrokmeier"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

#[languages]
#  [languages.en]
#    title = "Hello Friend NG"
#    subtitle = "A simple theme for Hugo"
#    keywords = ""
#    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
#    readOtherPosts = "Read other posts"
#
#    [languages.en.params.logo]
#      logoText = "hello friend ng"
#      logoHomeLink = "/"
#    # or
#    #
#    # path = "/img/your-example-logo.svg"
#    # alt = "Your example logo alt text"
#
#  # And you can even create generic menu
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"