baseURL = "https://pascalbrokmeier.de/"
languageCode = "en-us"
title = "Pascal Brokmeier"
theme= "hello-friend-ng"

[menu]
    [[menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "https://curiloo.com"
    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"
      
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Creative Lead Data Engineer & Cloud Architect at Quantum Black, AI by McKinsey"

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Homepage and blog of Pascal Brokmeier"
  keywords = "homepage, blog"
  images = [""]

  [params.portrait]
    path     = "/img/portrait_pascal_4_small.jpg"
    alt      = "Portrait"
    maxWidth = "150px"

  [params.logo]
    logoMark     = "$"
    logoText     = "PB >"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"


  [[params.social]]
    name = "email"
    url  = "mailto:public@pascalbrokmeier.de"

  [[params.social]]
    name = "github"
    url  = "https://github.com/pascalwhoop"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/pascalwhoop"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/1170940/pascalwhoop"

#   [[params.social]]
#     name = "unsplash"
#     url  = "https://unsplash.com/@pascalwhoop"
    
  [[params.social]]
    name = "telegram"
    url  = "https://telegram.me/pascalwhoop"

  [[params.social]]
    name = "goodreads"
    url  = "https://www.goodreads.com/user/show/101578711-pascal-brokmeier"

  [[params.social]]
    name = "keybase"
    url  = "https://keybase.io/pascalbrokmeier"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
